spring.application.name=EmployeeManagementSystem

spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

# Database URL
spring.datasource.url = jdbc:mysql://localhost:3306/ems_db

# Database credentials
spring.datasource.username = root
spring.datasource.password = Ekta@1204

# MySQL Driver
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

# Hibernate dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hibernate DDL Auto
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
spring.jpa.show-sql=true

# Format SQL
spring.jpa.properties.hibernate.format_sql=true

